sudo: required
language: python
python:
  - "3.6"

services:
  - docker

matrix:
  include:
  - python:
    env:
      - NAME="Django Inventory"
      - IMAGE_NAME=django-ansible-inventory
      - DOCKERFILE=Dockerfile
      - VERSION=v0.2

install: true

script: pytest || true ? # This is needed for the build to complete

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - flake8 --ignore=E501,E722,F401 --exclude=migrations || true ?
  - docker build --file $DOCKERFILE -t $IMAGE_NAME .
  - docker run -d -p 127.0.0.1:8000:8000 -e SECRET_KEY=${SECRET_KEY} --name compiled-docker $IMAGE_NAME
  - sleep 30
  - docker exec compiled-docker python manage.py shell < code/populate_database.py
  - sleep 5
  - ansible-inventory -i scripts/inventory.py --list
  - curl http://127.0.0.1:8000/api/
  - docker logs compiled-docker
  - docker ps -a

after_success:
- coveralls
