# Generated by Django 2.2.7 on 2019-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcustomer_yaml',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='historicalgroup_yaml',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='historicalsystem_yaml',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='historicalyaml',
            name='text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='yaml',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
