# Generated by Django 2.2.7 on 2019-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191126_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcustomer_yaml',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroup_yaml',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystem_yaml',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalyaml',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='text',
            field=models.TextField(default=None, null=True),
        ),
    ]
