# Generated by Django 2.2.7 on 2019-11-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191126_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='api.Group'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='group_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Group'),
        ),
    ]
