# Generated by Django 2.2.7 on 2019-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191128_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcustomer_yaml',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgroup_yaml',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsystem_yaml',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalyaml',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
