# Generated by Django 2.2.7 on 2019-12-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191128_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='yaml',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Customer_yaml'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='yaml',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Customer_yaml'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name',)},
        ),
    ]
